<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!--Model Shape Settings-->
    <xacro:arg name="name" default="robot"/>
    <!-- Laser Settings-->
    <xacro:arg name="laser_enable"  default="true"/>
    <xacro:arg name="laser_visualize"  default="true"/>
    <xacro:arg name="laser_update_rate"  default="10"/>
    <xacro:arg name="laser_samples"  default="360"/>
    <xacro:arg name="laser_min_angle"  default="-3.1415"/>
    <xacro:arg name="laser_max_angle"  default="3.1515"/>
    <xacro:arg name="laser_max_range"  default="6"/>
    <xacro:arg name="laser_range_resolution"  default="0.01"/>
    <xacro:arg name="laser_noise_stddev"  default="0.01"/>



    <joint name="lidar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="base_laser"/>
        <origin xyz="${$(arg length)/2} 0 0.01" rpy="0 0 0"/>
    </joint>

    <link name="base_laser">
       <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference= "base_laser">
        <material>Gazebo/Red</material>
        <xacro:if value="$(arg laser_enable)">

        <sensor name='gpu_lidar' type='gpu_lidar'>
            <always_on>true</always_on>
            <update_rate>$(arg laser_update_rate)</update_rate>
            <visualize>$(arg laser_visualize)</visualize>
            <pose>0 0 0 0 0 0</pose>
            <topic>/model/$(arg name)/scan</topic>
            <ignition_frame_id>$(arg name)/base_laser</ignition_frame_id>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>$(arg laser_samples)</samples>
                        <resolution>1</resolution>
                        <min_angle>$(arg laser_min_angle)</min_angle>
                        <max_angle>$(arg laser_max_angle)</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>0.01</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>$(arg laser_max_range)</max>
                    <resolution>$(arg laser_range_resolution)</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0</mean>
                    <stddev>$(arg laser_noise_stddev)</stddev>
                </noise>
            </ray>
        </sensor>
        </xacro:if>
        </gazebo>
    
</robot>